### ISSUE TITLE
Join channels at random intervals

### ISSUE THREAD

**Issue by MrYoranimo** [MrYoranimo/discord-voice-recorder-bot#2]
Allow admins to have the bot join at random intervals to spy on active voice channels.

**Comment by Ad-Blokker** [comment]
@MrYoranimo Made it so that the bot watches a change in voicechannel event. When a user joins. It joins the same voicechannel (when it has the appropriate permissions. When all normal users (so excluding bots) have left it will leave.

Joining at intervals is the next step
